# Generated by Django 4.0.5 on 2022-06-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0002_alter_product_brand_alter_product_madel'),
    ]

    operations = [
        migrations.AddField(
            model_name='madel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smartphone.brand'),
        ),
    ]
